from job import Job

class CircularQueue:
    def __init__(self): ...
    def enqueue(self, job: Job): ...
    def dequeue(self): ...
    def get_all_jobs(self) -> list: ...
    def is_full(self) -> bool: ...
    def is_empty(self) -> bool: ...
